[tox]
envlist =
    django32-py{39,310}
    django42-py{39,310,311,312}
    django51-py{310,311,312,313}
    django52-py{310,311,312,313}
    djangomain-{312,313}
    coverage-report

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311, coverage-report
    3.12: py312
    3.13: py313

[testenv]
deps =
    -r test-requirements.txt
    django32: django~=3.2.0
    django42: django~=4.2.0
    django51: django~=5.1.0
    django52: django~=5.2.0
    djangomain: https://github.com/django/django/archive/refs/heads/main.zip

setenv = COVERAGE_FILE=.coverage.{envname}
commands = python -m pytest --cov --cov-report term-missing:skip-covered

ignore_outcome =
    djangomain: true

[testenv:coverage-report]
deps = coverage
skip_install = true
setenv = COVERAGE_FILE=.coverage
commands =
    coverage combine
    coverage report
