[tox]
envlist =
    django32-py3{9,10}
    django42-py3{9,10,11,12}
    django52-py3{10,11,12,13,14}
    django60-py3{13,14}
    djangomain-py3{13,14}
    coverage-report

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311, coverage-report
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
deps =
    .[test]
    django32: django~=3.2.0
    django42: django~=4.2.0
    django51: django~=5.1.0
    django52: django~=5.2.0
    django60: django~=6.0.0
    djangomain: https://github.com/django/django/archive/refs/heads/main.zip

setenv = COVERAGE_FILE=.coverage.{envname}
commands = python -Wdefault -m pytest --cov --cov-report term-missing:skip-covered

ignore_outcome =
    djangomain: true

[testenv:coverage-report]
deps = coverage
skip_install = true
setenv = COVERAGE_FILE=.coverage
commands =
    coverage combine
    coverage report
